# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'FUENTE OVEJUNA SOCIAL'
description:      'Edición y archivo colaborativo. Sitio web en pruebas'
url:              'https://dxvidmr.github.io'
baseurl:          ''
copyright:        'David Merino Recalde 2024'
logo:             '/assets/logo.png'
default_thumb:    '/assets/default.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  fuenteovejuna: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'fuenteovejuna_item' # the layout for the pages to use
    metadata:
      source: 'fuenteovejuna.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/fuenteovejuna' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      fuenteovejuna:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - _date
          - _tags
          - description

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Aprende'
    sub:
      - label: 'Sobre el proyecto'
        link: '/proyecto/'
      - label: 'Sobre Fuente Ovejuna'
        link: '/Exhibiciones/'
      - label: 'Créditos'
        link: '/creditos/'
  - label: 'Edición'
    link: '/ediciondigital'
  - label: 'Archivo'
    link: '/archivo/'
  - label: 'Participa'
    link: '/participa/'
  - label: 'Descargas'
    link: '/descargas/'
  - label: '🔍︎'
    link: '/buscar/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/dxvidmr/pruebas-fo'
    - label: 'Créditos'
      link: '/credits'
  logos:
    - img: '/img/prolopesin.png'
      link: 'https://prolope.uab.cat/'

# FIN
